### ISSUE TITLE
fix: 모달 css 충돌 오류 해결

### ISSUE THREAD

**Issue by yezzan9** [Leets-Official/Weeth-FE#49]
## 1. 무엇을?
모달 css 충돌 수정

## 2. 상세 설명
- 어떤 순간부터 값자기 캘린더 페이지의 모달이 보이지 않음..
- but 버튼을 눌렀을 시 블러처리가 되므로 모달이 실행은 되었으나, css설정 오류로 인해 페이지에서 보이지 않게 된 것임 !

🔧 무엇이 문제일까...
CalendarHeader.jsx 파일 내부에 있는 modalStyles와
ModalAttend.css, ModalAttendCheck.css 파일의 css가 충돌하여 발생한 오류인 것을 확인함.
-> css 설정을 일부 통일하고, 각각의 파일에 css가 제대로 적용될 수 있도록 규칙 통일이 필요

## 3. 추가 사항
함께 해결해야함 .... @JIN921

**Comment by JIN921** [comment]
![image](https://github.com/user-attachments/assets/51d3fab5-2c99-4c5d-b74c-d6a223312a8f)
아마 이것 때문에 오류 생긴 것 같은데 이걸 스타일 컴포넌트로 만들어서 내 모달에만 적용되도록 수정해 볼게!
